version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      rust-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "tower-http"
          - "tuic-core"
          - "tuic-server"
      rust-security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: "tower-http"
      - dependency-name: "tuic-core"
      - dependency-name: "tuic-server"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      actions-dependencies:
        patterns:
          - "*"
      actions-security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/clash-dashboard"
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns:
          - "*"
      npm-security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"


